name: Reusable workflow

on:
  workflow_call:
    inputs:
      function-name:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: arc-runner-set

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Deploy Lambda Function
      uses: aws-actions/aws-lambda-deploy@v1.1.2
      with:
        function-name: ${{ inputs.function-name }}
        code-artifacts-dir: ${{ inputs.function-name }}
        handler: lambda_function.lambda_handler
        runtime: python3.14
        publish: true
        role: ${{ secrets.LAMBDA_EXECUTION_ROLE }}
